//! This file was generated and should not be edited directly.
//! The source code can be found at scripts/build.py

pub const TAG_ORDER: [&str; 76] = [
    "informal",
    "formal",
    "nominative",
    "genitive",
    "dative",
    "accusative",
    "vocative",
    "ablative",
    "locative",
    "partitive",
    "instrumental",
    "prepositional",
    "first-person",
    "second-person",
    "third-person",
    "first/second-person",
    "first/third-person",
    "first/second/third-person",
    "first-person-semantically",
    "second-person-semantically",
    "third-person-semantically",
    "singular",
    "plural",
    "plural-only",
    "definite",
    "indefinite",
    "masculine",
    "feminine",
    "neuter",
    "common-gender",
    "inanimate",
    "animate",
    "comparative",
    "positive",
    "superlative",
    "present",
    "past",
    "future",
    "future-i",
    "future-ii",
    "perfect",
    "pluperfect",
    "aorist",
    "imperfect",
    "conditional",
    "conditional-i",
    "conditional-ii",
    "imperative",
    "gerund",
    "imperfective",
    "perfective",
    "active",
    "passive",
    "participle",
    "subjunctive",
    "indicative",
    "adjective",
    "noun-from-verb",
    "infinitive",
    "adverbial",
    "emphatic",
    "relational",
    "diminutive",
    "poetic",
    "regional",
    "rare",
    "augmentative",
    "archaic",
    "with-genitive",
    "object-first-person",
    "object-second-person",
    "object-third-person",
    "object-singular",
    "object-plural",
    "negative",
    "combined-form",
];

#[rustfmt::skip]
pub const TAG_BANK: [(&str, &str, i32, &[&str], i32); 263] = [
    ("animate", "animacy", 0, &["animate"], 0),
    ("inanim", "animacy", 0, &["inanimate"], 0),
    ("dated", "archaism", 0, &["dated"], 0),
    ("obs", "archaism", 0, &["obsolete"], 0),
    ("out", "archaism", 0, &["outdated"], 0),
    ("arch", "archaism", 4, &["archaic"], -4),
    ("impf", "aspect", 0, &["imperfective"], 0),
    ("impf-only", "aspect", 0, &["imperfective only"], 0),
    ("pf", "aspect", 0, &["perfective"], 0),
    ("pf-only", "aspect", 0, &["perfective only"], 0),
    ("acc", "case", 0, &["with-accusative"], 0),
    ("dat", "case", 0, &["with-dative"], 0),
    ("def", "definiteness", 0, &["definite"], 0),
    ("indef", "definiteness", 0, &["indefinite"], 0),
    ("fem", "gender", -1, &["feminine"], 1),
    ("masc", "gender", -1, &["masculine"], 1),
    ("neut", "gender", -1, &["neuter"], 1),
    ("count", "grammar", 0, &["countable"], 0),
    ("gramm", "grammar", 0, &["grammar"], 0),
    ("interr", "grammar", 0, &["interrogative"], 0),
    ("not-comp", "grammar", 0, &["not comparable", "not-comparable"], 0),
    ("reltnl", "grammar", 0, &["relational"], 0),
    ("reltv", "grammar", 0, &["relative"], 0),
    ("uncount", "grammar", 0, &["uncountable"], 0),
    ("XS", "ipa", 0, &["X-SAMPA"], 0),
    ("abbv", "morphology", 0, &["abbreviation", "abbrev"], 0),
    ("aug", "morphology", 0, &["augmentative"], 0),
    ("circumfix", "morphology", 0, &["circumfix"], 0),
    ("circumpos", "morphology", 0, &["circumpos"], 0),
    ("contr", "morphology", 0, &["contraction"], 0),
    ("dim", "morphology", 0, &["diminutive"], 0),
    ("hypo", "morphology", 0, &["hypocoristic"], 0),
    ("indecl", "morphology", 0, &["indeclinable"], 0),
    ("infix", "morphology", 0, &["infix"], 0),
    ("init", "morphology", 0, &["initialism"], 0),
    ("interfix", "morphology", 0, &["interfix"], 0),
    ("irreg", "morphology", 0, &["irregular"], 0),
    ("neol", "morphology", 0, &["neologism"], 0),
    ("poss", "morphology", 0, &["possessive"], 0),
    ("name", "name", -1, &["name"], 1),
    ("surn", "name", 0, &["surname"], 0),
    ("in-pl", "number", 0, &["in the plural"], 0),
    ("in-sg", "number", 0, &["in the singular"], 0),
    ("no-pl", "number", 0, &["no-plural"], 0),
    ("pl", "number", 0, &["plural"], 0),
    ("pl-only", "number", 0, &["plural only", "plural-only"], 0),
    ("sg", "number", 0, &["singular"], 0),
    ("sg-only", "number", 0, &["singular only", "singular-only"], 0),
    ("card-num", "number-type", 0, &["cardinal number"], 0),
    ("frac-num", "number-type", 0, &["fractional number"], 0),
    ("ord-num", "number-type", 0, &["ordinal number"], 0),
    ("adj", "partOfSpeech", -1, &["adjective", "adj"], 1),
    ("adv", "partOfSpeech", -1, &["adverb", "adv"], 1),
    ("artic", "partOfSpeech", -1, &["article"], 1),
    ("conj", "partOfSpeech", -1, &["conjunction", "conj"], 1),
    ("det", "partOfSpeech", -1, &["determiner", "det"], 1),
    ("intj", "partOfSpeech", -1, &["interjection", "intj"], 1),
    ("n", "partOfSpeech", -1, &["noun"], 1),
    ("num", "partOfSpeech", -1, &["numeral", "num"], 1),
    ("phrase", "partOfSpeech", -1, &["phrase"], 1),
    ("pos-r", "partOfSpeech", -1, &["pos-root"], 1),
    ("postp", "partOfSpeech", -1, &["postposition", "postp"], 1),
    ("pref", "partOfSpeech", -1, &["prefix"], 1),
    ("prep", "partOfSpeech", -1, &["preposition", "prep"], 1),
    ("prep-phrase", "partOfSpeech", -1, &["prepositional phrase", "prep_phrase"], 1),
    ("pron", "partOfSpeech", -1, &["pronoun", "pron"], 1),
    ("prop-n", "partOfSpeech", -1, &["proper noun", "proper-noun"], 1),
    ("prov", "partOfSpeech", -1, &["proverb"], 1),
    ("ptcl", "partOfSpeech", -1, &["particle"], 1),
    ("ptcpl", "partOfSpeech", -1, &["participle"], 1),
    ("r", "partOfSpeech", -1, &["root"], 1),
    ("suf", "partOfSpeech", -1, &["suffix"], 1),
    ("v", "partOfSpeech", -1, &["verb"], 1),
    ("vdt", "partOfSpeech", -1, &["ditransitive verb", "ditransitive"], 1),
    ("vi", "partOfSpeech", -1, &["intransitive verb", "intransitive"], 1),
    ("vr", "partOfSpeech", -1, &["reflexive verb", "reflexive"], 1),
    ("vt", "partOfSpeech", -1, &["transitive verb", "transitive"], 1),
    ("child", "register", 0, &["childish"], 0),
    ("col", "register", 0, &["colloquial"], 0),
    ("crim-sl", "register", 0, &["criminal slang"], 0),
    ("defer", "register", 0, &["deferential"], 0),
    ("derog", "register", 0, &["derogatory"], 0),
    ("ethn-slr", "register", 0, &["ethnic slur"], 0),
    ("fan-sl", "register", 0, &["fandom slang"], 0),
    ("formal", "register", 0, &["formal"], 0),
    ("high-reg", "register", 0, &["higher register"], 0),
    ("humor", "register", 0, &["humorous", "jocular"], 0),
    ("imp", "register", 0, &["impolite"], 0),
    ("inf", "register", 0, &["informal"], 0),
    ("jar", "register", 0, &["jargon"], 0),
    ("ltrry", "register", 0, &["literary"], 0),
    ("mil-sl", "register", 0, &["military slang"], 0),
    ("net-sl", "register", 0, &["Internet slang"], 0),
    ("offens", "register", 0, &["offensive"], 0),
    ("pej", "register", 0, &["pejorative"], 0),
    ("poet", "register", 0, &["poetic"], 0),
    ("polite", "register", 0, &["polite"], 0),
    ("rlg-slr", "register", 0, &["religious slur"], 0),
    ("sl", "register", 0, &["slang"], 0),
    ("techncl", "register", 0, &["technical"], 0),
    ("txt-msg", "register", 0, &["text messaging"], 0),
    ("vern", "register", 0, &["vernacular"], 0),
    ("vulg", "register", 0, &["vulgar"], 0),
    ("youth-sl", "register", 0, &["youth slang"], 0),
    ("BDSM", "topic", 0, &["BDSM"], 0),
    ("Cath", "topic", 0, &["Roman Catholicism"], 0),
    ("Cath✝️", "topic", 0, &["Catholicism"], 0),
    ("Hind🛕", "topic", 0, &["Hinduism"], 0),
    ("LGBT", "topic", 0, &["LGBT"], 0),
    ("OOP", "topic", 0, &["object-oriented programming"], 0),
    ("Prot✝️", "topic", 0, &["Protestantism"], 0),
    ("agr", "topic", 0, &["agriculture"], 0),
    ("anat", "topic", 0, &["anatomy"], 0),
    ("anthro", "topic", 0, &["anthropology"], 0),
    ("archae", "topic", 0, &["archaeology"], 0),
    ("archit", "topic", 0, &["architecture"], 0),
    ("arithm", "topic", 0, &["arithmetic"], 0),
    ("art", "topic", 0, &["art"], 0),
    ("astrol", "topic", 0, &["astrology"], 0),
    ("astrophys", "topic", 0, &["astrophysics"], 0),
    ("auto", "topic", 0, &["automotive"], 0),
    ("avio", "topic", 0, &["aviation"], 0),
    ("bank", "topic", 0, &["banking"], 0),
    ("bible", "topic", 0, &["biblical"], 0),
    ("biochem", "topic", 0, &["biochemistry"], 0),
    ("biol", "topic", 0, &["biology"], 0),
    ("bus💼", "topic", 0, &["business"], 0),
    ("cards", "topic", 0, &["card games"], 0),
    ("chem", "topic", 0, &["chemistry"], 0),
    ("chess", "topic", 0, &["chess"], 0),
    ("comp", "topic", 0, &["computing"], 0),
    ("comp-sci", "topic", 0, &["computer science"], 0),
    ("cook", "topic", 0, &["cooking"], 0),
    ("cyto", "topic", 0, &["cytology"], 0),
    ("ecc", "topic", 0, &["ecclesiastical"], 0),
    ("eco", "topic", 0, &["ecology"], 0),
    ("econ", "topic", 0, &["economics"], 0),
    ("edu", "topic", 0, &["education"], 0),
    ("electr", "topic", 0, &["electronics"], 0),
    ("eng", "topic", 0, &["engineering"], 0),
    ("entom", "topic", 0, &["entomology"], 0),
    ("film", "topic", 0, &["film"], 0),
    ("fin", "topic", 0, &["finance"], 0),
    ("firearm", "topic", 0, &["firearms"], 0),
    ("game", "topic", 0, &["video games"], 0),
    ("gen🧬", "topic", 0, &["genetics"], 0),
    ("geo", "topic", 0, &["geography"], 0),
    ("geol", "topic", 0, &["geology"], 0),
    ("geom", "topic", 0, &["geometry"], 0),
    ("golf", "topic", 0, &["golf"], 0),
    ("greek-myth", "topic", 0, &["Greek mythology"], 0),
    ("gymn", "topic", 0, &["gymnastics"], 0),
    ("herald", "topic", 0, &["heraldry"], 0),
    ("hist", "topic", 0, &["historical"], 0),
    ("history", "topic", 0, &["history"], 0),
    ("hunt", "topic", 0, &["hunting"], 0),
    ("immun", "topic", 0, &["immunology"], 0),
    ("inorg-chem", "topic", 0, &["inorganic chemistry"], 0),
    ("journ📰", "topic", 0, &["journalism"], 0),
    ("law", "topic", 0, &["law"], 0),
    ("ling", "topic", 0, &["linguistics"], 0),
    ("log", "topic", 0, &["logic"], 0),
    ("math", "topic", 0, &["mathematics"], 0),
    ("mech", "topic", 0, &["mechanics"], 0),
    ("med", "topic", 0, &["medicine"], 0),
    ("metal", "topic", 0, &["metallurgy"], 0),
    ("meteo", "topic", 0, &["meteorology"], 0),
    ("mil", "topic", 0, &["military"], 0),
    ("mine⛏️", "topic", 0, &["mining"], 0),
    ("music", "topic", 0, &["music"], 0),
    ("myco", "topic", 0, &["mycology"], 0),
    ("myth", "topic", 0, &["mythology"], 0),
    ("net", "topic", 0, &["Internet"], 0),
    ("org-chem", "topic", 0, &["organic chemistry"], 0),
    ("ornit", "topic", 0, &["ornithology"], 0),
    ("paleo", "topic", 0, &["paleontology"], 0),
    ("path", "topic", 0, &["pathology"], 0),
    ("pharma", "topic", 0, &["pharmacology"], 0),
    ("philos", "topic", 0, &["philosophy"], 0),
    ("phonet", "topic", 0, &["phonetics"], 0),
    ("phonol", "topic", 0, &["phonology"], 0),
    ("photo", "topic", 0, &["photography"], 0),
    ("physics", "topic", 0, &["physics"], 0),
    ("physio", "topic", 0, &["physiology"], 0),
    ("poetry", "topic", 0, &["poetry"], 0),
    ("poker", "topic", 0, &["poker"], 0),
    ("polit", "topic", 0, &["politics"], 0),
    ("program", "topic", 0, &["programming"], 0),
    ("psych", "topic", 0, &["psychology"], 0),
    ("rail", "topic", 0, &["rail transport"], 0),
    ("rhet", "topic", 0, &["rhetoric"], 0),
    ("rome-myth", "topic", 0, &["Roman mythology"], 0),
    ("school", "topic", 0, &["school"], 0),
    ("sci-fi", "topic", 0, &["science fiction"], 0),
    ("socio", "topic", 0, &["sociology"], 0),
    ("soft", "topic", 0, &["software"], 0),
    ("soft-eng", "topic", 0, &["software engineering"], 0),
    ("sports", "topic", 0, &["sports"], 0),
    ("stat", "topic", 0, &["statistics"], 0),
    ("sumo", "topic", 0, &["sumo"], 0),
    ("surg", "topic", 0, &["surgery"], 0),
    ("tech", "topic", 0, &["technology"], 0),
    ("theater", "topic", 0, &["theater"], 0),
    ("theo", "topic", 0, &["theology"], 0),
    ("tv", "topic", 0, &["television"], 0),
    ("txnmy", "topic", 0, &["taxonomy"], 0),
    ("vehic", "topic", 0, &["vehicles"], 0),
    ("zoo", "topic", 0, &["zoology"], 0),
    ("ૐ", "topic", 0, &["Buddhism"], 0),
    ("☪️", "topic", 0, &["Islam"], 0),
    ("⚽", "topic", 0, &["soccer"], 0),
    ("⛪", "topic", 0, &["modern Italianate Ecclesiastical"], 0),
    ("✒️clgphy", "topic", 0, &["calligraphy"], 0),
    ("✝️", "topic", 0, &["Christianity"], 0),
    ("✡️", "topic", 0, &["Judaism"], 0),
    ("🌿", "topic", 0, &["botany"], 0),
    ("🎾ten", "topic", 0, &["tennis"], 0),
    ("👷", "topic", 0, &["construction"], 0),
    ("📐trig", "topic", 0, &["trigonometry"], 0),
    ("📚lit", "topic", 0, &["literature"], 0),
    ("🔭", "topic", 0, &["astronomy"], 0),
    ("🚢", "topic", 0, &["nautical"], 0),
    ("🛐", "topic", 0, &["religion"], 0),
    ("🧵", "topic", 0, &["textiles"], 0),
    ("🪙", "topic", 0, &["numismatics"], 0),
    ("🫀", "topic", 0, &["cardiology"], 0),
    ("🪨", "topic", 1, &["mineralogy"], -1),
    ("aux", "transitivity", 0, &["auxiliary"], 0),
    ("aux-v", "transitivity", 0, &["auxiliary verb"], 0),
    ("cop", "transitivity", 0, &["copulative"], 0),
    ("impers", "transitivity", 0, &["impersonal"], 0),
    ("pers", "transitivity", 0, &["personal"], 0),
    ("ref-pron", "transitivity", 0, &["takes a reflexive pronoun"], 0),
    ("cmn", "usage", 0, &["common"], 0),
    ("dialect", "usage", 0, &["dialectal", "dialect"], 0),
    ("euph", "usage", 0, &["euphemistic"], 0),
    ("fig", "usage", 0, &["figuratively", "figurative"], 0),
    ("idio", "usage", 0, &["idiomatic"], 0),
    ("ltrl", "usage", 0, &["literal"], 0),
    ("ltrly", "usage", 0, &["literally"], 0),
    ("non-std", "usage", 0, &["nonstandard"], 0),
    ("regio", "usage", 0, &["regional"], 0),
    ("uncmmn", "usage", 0, &["uncommon"], 0),
    ("rare", "usage", 1, &["rare"], -1),
    ("Alemannic", "variety", 0, &["Alemannic"], 0),
    ("Bavarian", "variety", 0, &["Bavarian"], 0),
    ("Swabian", "variety", 0, &["Swabian"], 0),
    ("🇦🇹", "variety", 0, &["Austria", "Austrian German"], 0),
    ("🇨🇭", "variety", 0, &["Switzerland", "Swiss Standard German"], 0),
    ("🇩🇪", "variety", 0, &["Germany"], 0),
    ("🇩🇪➡️", "variety", 0, &["East Germany"], 0),
    ("🇩🇪⬅️", "variety", 0, &["western Germany", "Western"], 0),
    ("🇩🇪⬆️", "variety", 0, &["North German", "Northern Germany", "Northern-Germany"], 0),
    ("🇩🇪⬇️", "variety", 0, &["South German", "South-German", "Southern German"], 0),
    ("🇩🇪🎯⬆️", "variety", 0, &["northern and central Germany"], 0),
    ("🇱🇮", "variety", 0, &["Liechtenstein"], 0),
    ("char", "", 0, &["character"], 0),
    ("mix", "", 0, &["mixed"], 0),
    ("punct", "", 0, &["punct"], 0),
    ("strong", "", 0, &["strong"], 0),
    ("symb", "", 0, &["symbol"], 0),
    ("weak", "", 0, &["weak"], 0),
    ("non-lemma", "", 10, &["non-lemma"], -10),
];

pub const POSES: [(&str, &str); 41] = [
    ("adjective", "adj"),
    ("adj", "adj"),
    ("adverb", "adv"),
    ("adv", "adv"),
    ("article", "artic"),
    ("conjunction", "conj"),
    ("conj", "conj"),
    ("determiner", "det"),
    ("det", "det"),
    ("interjection", "intj"),
    ("intj", "intj"),
    ("noun", "n"),
    ("numeral", "num"),
    ("num", "num"),
    ("phrase", "phrase"),
    ("pos-root", "pos-r"),
    ("postposition", "postp"),
    ("postp", "postp"),
    ("prefix", "pref"),
    ("preposition", "prep"),
    ("prep", "prep"),
    ("prepositional phrase", "prep-phrase"),
    ("prep_phrase", "prep-phrase"),
    ("pronoun", "pron"),
    ("pron", "pron"),
    ("proper noun", "prop-n"),
    ("proper-noun", "prop-n"),
    ("proverb", "prov"),
    ("particle", "ptcl"),
    ("participle", "ptcpl"),
    ("root", "r"),
    ("suffix", "suf"),
    ("verb", "v"),
    ("ditransitive verb", "vdt"),
    ("ditransitive", "vdt"),
    ("intransitive verb", "vi"),
    ("intransitive", "vi"),
    ("reflexive verb", "vr"),
    ("reflexive", "vr"),
    ("transitive verb", "vt"),
    ("transitive", "vt"),
];
